# Generated by Django 4.2.1 on 2023-05-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Enter email address', max_length=50, unique=True)),
                ('first_name', models.CharField(help_text='Enter first name', max_length=30)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=30)),
                ('phone_number', models.CharField(help_text='Enter phone number', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the gym', max_length=20)),
                ('open_time', models.TimeField(help_text='Gym opening time')),
                ('close_time', models.TimeField(help_text='Gym closing time')),
                ('address', models.CharField(help_text='Address of the gym', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GymMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of gym membership', max_length=20)),
                ('description', models.TextField(help_text='Description of gym membership', max_length=200)),
                ('cost', models.IntegerField(help_text='Cost of the gym membership', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=30)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=30)),
                ('price_per_hour', models.IntegerField(help_text='Pprice per hour of training', max_length=3)),
                ('specialization', models.TextField(help_text='Info about treiner specialization', max_length=150)),
            ],
        ),
    ]
