# Generated by Django 4.2.1 on 2023-06-05 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub_core', '0002_schedule_delete_client_delete_trainer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the group class', max_length=20)),
                ('description', models.TextField(help_text='Description of the group class', max_length=200)),
                ('gym', models.ForeignKey(help_text='Gym of the group class', null=True, on_delete=django.db.models.deletion.CASCADE, to='fitnessclub_core.gym')),
            ],
        ),
    ]
