# Generated by Django 4.2.1 on 2023-06-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub_core', '0003_groupclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='gym_membership',
            field=models.ManyToManyField(help_text='Gym membership of the gym', null=True, to='fitnessclub_core.gymmembership'),
        ),
    ]
