# Generated by Django 4.2.1 on 2023-06-06 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub_core', '0004_alter_gym_gym_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='gym',
            field=models.ForeignKey(help_text='Gym of the group class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_classes', to='fitnessclub_core.gym'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='gym_membership',
            field=models.ManyToManyField(blank=True, help_text='Gym membership of the gym', to='fitnessclub_core.gymmembership'),
        ),
    ]
