# Generated by Django 4.2.1 on 2023-06-06 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub_core', '0005_alter_groupclass_gym_alter_gym_gym_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='gym_membership',
            field=models.ManyToManyField(blank=True, help_text='Gym membership of the gym', related_name='gyms', to='fitnessclub_core.gymmembership'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='schedule',
            field=models.ForeignKey(help_text='Schedule of the gym', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms', to='fitnessclub_core.schedule'),
        ),
    ]
