# Generated by Django 4.2.1 on 2023-06-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub_core', '0006_alter_gym_gym_membership_alter_gym_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='cost',
            field=models.IntegerField(default=0, help_text='Cost of the group class'),
        ),
    ]
