# Generated by Django 4.2.1 on 2023-09-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub_core', '0008_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='preview',
            field=models.TextField(default=''),
        ),
    ]
