# Generated by Django 4.2.1 on 2023-09-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub_core', '0010_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer',
            new_name='reviewer_name',
        ),
    ]
