# Generated by Django 4.2.1 on 2023-09-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessclub_core', '0012_rename_reviewer_name_review_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=66)),
                ('answer', models.CharField(max_length=666)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
